#!/usr/bin/env bash
#**********************************************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Script generated by Vivado on Fri Feb 06 12:11:14 +0530 2026
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : design_1.sh
# Simulator    : Synopsys Verilog Compiler Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : design_1.sh
#                design_1.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                design_1.sh [-reset_run]
#                design_1.sh [-reset_log]
#                design_1.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'design_1.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set vhdlan compile options
vhdlan_opts="-full64 -l .tmp_log"

# set vlogan compile options
vlogan_opts="-full64 -l .tmp_log"

# set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc -t ps -licqueue -l elaborate.log"

# set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log "

# set design libraries
design_libs=(xpm xil_defaultlib xlconstant_v1_1_9 xbip_utils_v3_0_14 axi_utils_v2_0_10 c_reg_fd_v12_0_10 xbip_dsp48_wrapper_v3_0_6 xbip_pipe_v3_0_10 c_addsub_v12_0_19 c_shift_ram_v12_0_18 mult_gen_v12_0_22 floating_point_v7_1_19 cmpy_v6_0_25 floating_point_v7_0_24 xfft_v9_1_13 xlconcat_v2_1_6)

# simulation root library directory
sim_lib_dir="vcs_lib"

# script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2024.2 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xpm $vlogan_opts -sverilog +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/3cbc" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" \
  "/tools/Vivado_2024_2/Vivado/2024.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "/tools/Vivado_2024_2/Vivado/2024.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee compile.log; cat .tmp_log > vlogan.log 2>/dev/null

  vhdlan -work xpm $vhdlan_opts \
  "/tools/Vivado_2024_2/Vivado/2024.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/3cbc" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" \
  "../../../bd/design_1/ip/design_1_adc_interface_0_0/sim/design_1_adc_interface_0_0.v" \
  "../../../bd/design_1/ip/design_1_vco_interface_0_0/sim/design_1_vco_interface_0_0.v" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xlconstant_v1_1_9 $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/3cbc" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/e2d2/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/3cbc" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" \
  "../../../bd/design_1/ip/design_1_xlconstant_0_0/sim/design_1_xlconstant_0_0.v" \
  "../../../bd/design_1/ip/design_1_clock_divider_0_0/sim/design_1_clock_divider_0_0.v" \
  "../../../bd/design_1/ip/design_1_ila_0_1/sim/design_1_ila_0_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xbip_utils_v3_0_14 $vhdlan_opts \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/b27f/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work axi_utils_v2_0_10 $vhdlan_opts \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7e77/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work c_reg_fd_v12_0_10 $vhdlan_opts \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/47fd/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xbip_dsp48_wrapper_v3_0_6 $vhdlan_opts \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/f596/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xbip_pipe_v3_0_10 $vhdlan_opts \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/d531/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work c_addsub_v12_0_19 $vhdlan_opts \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/a1b8/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work c_shift_ram_v12_0_18 $vhdlan_opts \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/fe8a/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work mult_gen_v12_0_22 $vhdlan_opts \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/e765/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work floating_point_v7_1_19 $vhdlan_opts \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/bf3d/hdl/floating_point_v7_1_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work floating_point_v7_1_19 $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/3cbc" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/bf3d/hdl/floating_point_v7_1_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work cmpy_v6_0_25 $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/3cbc" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/01d8/hdl/cmpy_v6_0_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work cmpy_v6_0_25 $vhdlan_opts \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/01d8/hdl/cmpy_v6_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work floating_point_v7_0_24 $vhdlan_opts \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/f38a/hdl/floating_point_v7_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xfft_v9_1_13 $vhdlan_opts -vhdl08 \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/float_pkg.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/cfloat_pkg.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/DELAY.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/CDELAY.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/BDELAY.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/DS.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/CB.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/DSN.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/DSPFP32_GW.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/InputSwap.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/PARFFT2.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/PARFFT4.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/PARFFT.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/R2BUTTERFLY.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/R2TableFP32_pkg.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/R2TableFP32.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/R4BUTTERFLY.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/R4TableFP32_pkg.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/R4TableFP32.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/STAGE.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/SystolicFFT.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/xfft_v9_1_core_ssr.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xfft_v9_1_13 $vhdlan_opts \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/xfft_v9_1_viv_comp.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/xfft_v9_1_comp.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/pkg.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/half_sincos_tw_table.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/quarter_sin_tw_table.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/quarter2_sin_tw_table.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/adder.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/adder_bypass.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/logic_gate.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/equ_rtl.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/cnt_sat.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/cnt_tc_rtl.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/cnt_tc_rtl_a.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/cnt_tc_rtl_b.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/shift_ram.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/srl_fifo.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/mux_bus2.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/mux_bus4.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/mux_bus8.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/mux_bus16.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/mux_bus32.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/dist_mem.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/dpm.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/dpm_hybrid.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/reg_rs_rtl.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/sub_byp.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/sub_byp_j.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/subtracter.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/xor_bit_gate.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/arith_shift1.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/arith_shift3.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/butterfly_dsp48e.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/butterfly_dsp48e_hybrid.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/butterfly_dsp48e_bypass.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/butterfly_dsp48e_bypass_hybrid.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/butterfly_dsp48e_mul_j_bypass.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/butterfly_dsp48e_mul_j_bypass_hybrid.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/butterfly_dsp48e_simd.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/butterfly_dsp48e_simd_bypass.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/butterfly_dsp48e_simd_mul_j_bypass.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/bf_dsp.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/bf_dsp_bypass.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/bf_dsp_mul_j_bypass.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/bfly_byp.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/bfly_byp_j.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/butterfly.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/twos_comp.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/cmpy.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/dfly_byp.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/dragonfly_dsp48_bypass.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/so_xk_counter.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/flow_control_b.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/flow_control_c.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/max2_2.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/in_ranger.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/in_switch4.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/out_addr_gen_b.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/out_switch4.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/overflow_gen.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/unbiased_round.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/pe4.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r2_in_addr.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r2_ovflo_gen.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r2_pe.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/range_r2.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r2_ranger.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r2_rw_addr.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r2_tw_addr.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/twgen_distmem.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/twgen_distmem_so.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/twgen_half_sincos.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/twgen_quarter_sin.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/twiddle_gen.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r2_control.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/scale_logic.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r2_datapath.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/rw_addr_gen_b.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/tw_gen_p2.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/tw_gen_p4.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/tw_addr_gen.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r4_control.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/range_r4.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r4_ranger.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r4_datapath.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r22_twos_comp_mux.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r22_delay_mux.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r22_srl_memory.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r22_memory.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r22_bfly_byp.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r22_bf.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r22_bf_sp.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r22_cnt_ctrl.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r22_flow_ctrl.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r22_ovflo.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r22_busy.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r22_tw_gen.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r22_pe.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r22_right_shift.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r22_shift_decode.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/r22_var_unbiased_round.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/so_n_counter.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/so_io_addr_gen.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/so_run_addr_gen_rotator.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/so_run_addr_gen_left_shift.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/so_run_addr_gen.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/so_addr_gen.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/so_control_fsm.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/so_control.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/so_memory.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/so_ranger.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/so_datapath.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/pipe_blank.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/fp_get_block_max_exp.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/fp_convert_to_block_fp.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/fp_convert_to_fp.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/fp_shift_ram_clr_op.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/xfft_v9_1_axi_pkg.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/axi_wrapper_input_fifo.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/axi_wrapper_output_fifo.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/axi_wrapper.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/xfft_v9_1_b.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/xfft_v9_1_c.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/xfft_v9_1_d.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/xfft_v9_1_e.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/xfft_v9_1_fp.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/xfft_v9_1_core.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/xfft_v9_1_viv.vhd" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/7162/hdl/xfft_v9_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/design_1/ip/design_1_xfft_0_0/sim/design_1_xfft_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/3cbc" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" \
  "../../../bd/design_1/ip/design_1_xlconstant_1_0/sim/design_1_xlconstant_1_0.v" \
  "../../../bd/design_1/ip/design_1_xlconstant_2_0/sim/design_1_xlconstant_2_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xlconcat_v2_1_6 $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/3cbc" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" \
  "../../../../project_1.gen/sources_1/bd/design_1/ipshared/6120/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/3cbc" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" +incdir+"../../../../project_1.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" \
  "../../../bd/design_1/ip/design_1_xlconcat_0_0/sim/design_1_xlconcat_0_0.v" \
  "../../../bd/design_1/sim/design_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($lib_map_path == "") ]]; then
    lib_map_path="/home/selaka/Desktop/adc_testing/v1/project_1/project_1.cache/compile_simlib/vcs"
  fi

  echo "LIBRARY_SCAN=TRUE" >> $file

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .tmp_log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log lib_sc.so 64 AN.DB csrc design_1_simv.daidir vcs_lib c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(vlogan.log vhdlan.log compile.log elaborate.log simulate.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-step]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-reset_log]\n\
Usage: design_1.sh [-keep_index]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (compile, elaborate, simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
