# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/selaka/Desktop/adc_testing/v1/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_adc_interface_0_0/design_1_adc_interface_0_0.xci
# IP: The module: 'design_1_adc_interface_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/selaka/Desktop/adc_testing/v1/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# IP: /home/selaka/Desktop/adc_testing/v1/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: /home/selaka/Desktop/adc_testing/v1/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_adc_interface_0_0/design_1_adc_interface_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_adc_interface_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/selaka/Desktop/adc_testing/v1/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_adc_interface_0_0/design_1_adc_interface_0_0.xci
# IP: The module: 'design_1_adc_interface_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/selaka/Desktop/adc_testing/v1/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# IP: /home/selaka/Desktop/adc_testing/v1/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: /home/selaka/Desktop/adc_testing/v1/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_adc_interface_0_0/design_1_adc_interface_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_adc_interface_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
